config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, :only => [:index, :show]
  
  root to: 'high_voltage/pages#show', id: 'home'
  get '/search' => 'search#search', :as => :search
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  resources :episodes do 
    member do
      post :annotate
      get :dope
      get :nope
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/episode.rb
# coding: utf-8
class Episode < ActiveRecord::Base
  # I guess you can only set default values for the second argument...
  scope :by_direction, ->(direction = :asc) { order(number: direction.to_sym).order(slug: direction.to_sym)}
  scope :by_topic, ->(topic) { tagged_with(topic) }

  has_attached_file :audio_track
  validates_attachment_content_type :audio_track, content_type: /^audio/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /^video/
  
  
  # Search stuffs
  include PgSearch
  pg_search_scope :search, :associated_against => {
    episode_timestamps: :description
  }
  multisearchable against: :description

  ##
  # Associations
  has_many :episode_timestamps, inverse_of: :episode
  accepts_nested_attributes_for :episode_timestamps

  acts_as_votable
  acts_as_taggable_on :topics
  acts_as_punchable
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  paginates_per 100
  
  def wecks_date_format
    published_at.strftime('%m.%d.%y')
  end

  def media_type_enum
    %w(audio video)
  end
  
  def prev
    Episode.where(Episode.arel_table[:number].lt(self.number))
      .order(number: :desc)
      .order(slug: :desc).first
  end

  def next
    Episode.where(Episode.arel_table[:number].gt(self.number))
      .order(number: :asc)
      .order(slug: :asc).first
  end

  def download_episode
    if media_type.eql? 'audio'
      download_file 'audio_track'
    elsif media_type.eql? 'video'
      download_file 'video'
    end
  end

  # Downloads the file as a temp file
  # saves it to the model file_type passed in
  # => file_type - can be :audio_track or :video
  def download_file(file_type)
    temp_file = File.new(public_url.split('/').last, "wb")
    remote_data = open(URI.parse(public_url))
    temp_file.write(remote_data.read)
    update_attributes(file_type => temp_file)
    File.delete temp_file
  end

  def audio_url
    if audio_track_file_name
      audio_track.url
    else
      public_url
    end
  end

  def audio_download_url
    if audio_track_file_name
      audio_track.url(:original, false)
    else
      public_url
    end
  end
  
  def parse_timestamps
    unparsed = 0
    nodescription = 0
    full_timestamp = 0
    doc = Nokogiri::HTML(wecks_entry)
    topic_name = "NOTTATOPIC"
    doc.css("p").each do |p|
      # Next if this is just the category episode thing
      next if p.text.eql? "Category:Episodes"
      # Next if this is italics (usually air date)
      next if p.children.first.name.eql?  "i"
      # set the topic name of the bold element
      topic_name = p.children.first.text if p.children.first.name.eql? "b"
      # Next if there is no topic set
      next if topic_name.eql? "NOTTATOPIC"
      timestamp = ""
      if p.text[/^((\d+):)?(\d+):?(\d{2})\s*–*-* (.+)$/]
        hour = $2.to_i
        minute = $3.to_i
        second = $4.to_i
        total_seconds = (hour * 3600) + (minute * 60) + second
        description = $5
        timestamp = "hour: #{hour} minute: #{minute} second: #{second} #{description}"
        episode_timestamp = EpisodeTimestamp.find_or_create_by(timestamp: total_seconds,
                                                               description: description,
                                                               episode: self
                                                              )
        topic_list.add(topic_name)
        save
        episode_timestamp.topic_list.add(topic_name)
        episode_timestamp.save
        full_timestamp += 1
      elsif p.text[/^(\d{2})*:*(\d{2}):(\d{2})/]
        hour = $1
        minute = $2
        second = $3
        timestamp = "hour: #{hour} minute: #{minute} second: #{second}"
        nodescription += 1
      else
        next if topic_name.eql? "Seatbelts"
        next if topic_name.eql? p.text
        unparsed += 1
      end
    end
  end
  
  protected 

    rails_admin do
      configure :episode_timestamps do
        inverse_of :episode
      end
      list do
        sort_by :number
        field :title
        field :number do
          sort_reverse true
        end
        field :published_at
        field :description
      end
      edit do
        field :title
        field :description, :wysihtml5
        field :media_type
        field :public_url
        field :published_at
        field :number
        field :wecks_entry
        field :slug
        field :episode_timestamps
      end
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  respond_to :html, :json, :rss, :xml
  custom_actions resource: [:dope, :nope]
  after_filter :punch, only: :show
  has_scope :by_direction, default: 'asc', allow_blank: true, only: :index
  has_scope :by_topic
  has_scope :search
  has_scope :page

  def dope
    dope! do |format| 
      if current_user
        current_user.likes @episode
        format.html {redirect_to :back}
      else
        flash[:error] = "You must login before voting!"
        format.html {redirect_to :back}
      end
    end
  end

  def nope
    nope! do |format|
      if current_user
        current_user.dislikes @episode
        format.html {redirect_to :back}
      else
        flash[:error] = "You must login before voting!"
        format.html {redirect_to :back}
      end
    end
  end

  def punch
    @episode.punch(request)
  end

  def annotate
    if resource.episode_timestamps.create(timestamp: params[:timestamp], description: params[:description]).persisted?
      render json: nil, status: :ok
    else
      render json: nil, status: :unprocessable_entity
    end
  end
  
  protected
  def collection
    if params[:all_episodes] and params[:format].eql? 'rss'
      @episodes ||= end_of_association_chain
    else
      @episodes ||= end_of_association_chain.page(params[:page])
    end
  end
end

app/views/episodes/_annotate.html.haml
%script{ type: 'text/x-handlebars' }
  {{ outlet }}

app/views/episodes/_media.html.haml
- if @episode.media_type.eql? "video"
  %video.video{controls: "controls", preload: 'none'}
    %source{src: @episode.public_url, type:'video/mp4'}
    %source{src: @episode.public_url.gsub("mp4", "ogg"), type:'video/ogv'}
    %source{src: @episode.public_url.gsub("mp4", "webm"), type:'video/webm'}

app/views/episodes/index.html.haml
%h2 Episode Archive
.page-info #{page_entries_info @episodes}
- if params[:by_topic]
  %h4= "Filtered by topic: #{params[:by_topic]}"
.col-md-12= paginate @episodes
.col-md-12.episodes
  - @episodes.each do |episode|
    = link_to episode_path(episode) do
      .col-md-3.col-sm-4.col-xs-12
        .episode.episode-card
          .header-box
            .image
          .episode-info
            .episode-title= link_to episode.title, episode_path(episode)
            .episode-date= episode.published_at.strftime("%d %b %y")
.clearfix
.col-md-12= paginate @episodes

app/views/episodes/show.html.haml
.episode-show.episodes
  .episode.episode-basic-info.jp-audio#jp_container_1{"aria-label" => "media player", :role => "application"}
    .episode-basic-info-box.col-md-3.col-sm-6.col-xs-12
      .header-box
        .episode-show-image
      .episode-info
        .episode-title= @episode.title
        .episode-date= @episode.published_at.strftime("%d %b %y")
        .action-buttons
          = link_to dope_episode_path(@episode) do
            .dope-link
              %span.glyphicon.glyphicon-thumbs-up{title: 'Dope'}
          .votes-total= @episode.cached_votes_score
          = link_to nope_episode_path(@episode) do
            .nope-link
              %span.glyphicon.glyphicon-thumbs-down{title: 'Nope'}
          .action-button.download-button
            = link_to(@episode.audio_download_url, download: "uyd-episode-#{@episode.number}_#{@episode.wecks_date_format}.mp3", title: "Download") do
              .fell-off-link
                %span.glyphicon.glyphicon-download-alt
      .episode-playback
        .playback-buttons.action-buttons
          - if @episode.prev
            .action-button.episode-prev
              = link_to episode_path(@episode.prev) do
                %span.glyphicon.glyphicon-step-backward{title: @episode.prev.title}
          .jp-pause.glyphicon.glyphicon-pause.episode-pause{:role => "button", :tabindex => "0"}
          .jp-play.glyphicon.glyphicon-play.episode-play{:role => "button", :tabindex => "0"}
          - if @episode.next            
            .action-button.episode-next
              = link_to episode_path(@episode.next) do
                %span.glyphicon.glyphicon-step-forward{title: @episode.next.title}
    .episode-description.col-md-9.col-sm-6.col-xs-12
      - if @episode.description
        .description
          %b.description-label Description
          .description-text= @episode.description.html_safe
      - unless @episode.topics.empty?
        .topics
          %b.topics-label Topics
          .topic-list= @episode.topic_list.to_sentence || "There are no topics attributed to this episode yet."
    .clearfix
    .episode-playback-bar.col-md-12
      .jp-progress
        .jp-seek-bar#seekbar
          .jp-play-bar#playbar
        .playback-time
          .jp-current-time
          .jp-duration
  = render "media"

.clearfix
%ul.nav.nav-tabs.episode-show{role:"tablist"}
  %li.active= link_to "Timestamps", "#timestamps", role: "tab", data: {toggle: "tab"}
  %li= link_to "Weck's Entry", "#wecks", role: "tab", data: {toggle: "tab"}
.tab-content
  - if @episode.episode_timestamps.any?
    .timestamps.tab-pane.active#timestamps
      - @episode.episode_timestamps.each do |timestamp|
        .timestamp 
          .timestamp-seconds{data: {timestamp_seconds: timestamp.timestamp}}= timestamp.display_timestamp
          .timestamp-topic.btn-default.btn-xs
            - timestamp.topic_list.each do |topic_name|
              = link_to topic_name, episodes_path(by_topic: topic_name)
          .timestamp-description= timestamp.description.html_safe

  - else
    %i There are no timestamps yet.
  .wecks-entry.content.tab-pane#wecks
    .entry= @episode.wecks_entry.try(:html_safe)
  .annotation.tab-pane#annotate
    %i Here is where you'll be able to add more timestamps.  Feature to be in place by August 24th.
    = render partial: 'annotate'
#comments
  .fb-comments{data: {href: request.original_url, numposts: "20", colorscheme: "light", width: '100%'} }

- content_for :facebook_meta do
  %meta{property: "og:title", content: "UYD #{@episode.title}" }
  - unless @episode.description.blank?
    %meta{property: "og:description", content: truncate(@episode.description, length: 75, omission: "...", separator: " ")}
  - else
    %meta{property: "og:description", content: "The Uhh Yeah Dude dancecast #{@episode.title}"}
  %meta{property: "og:image", content: image_url('uyd-fb-meta.jpg')}

- content_for :title do 
  UYD #{@episode.title}
- content_for :description do
  UYD #{@episode.title}