config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :users, :only => [:index, :show]
  
  root to: 'high_voltage/pages#show', id: 'home'
  get '/search' => 'search#search', :as => :search
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  resources :episodes do 
    member do
      post :annotate
      get :dope
      get :nope
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        .archive-icon= image_tag 'archive-icon.png'
      .search-bar.hidden-xs.desktop= render 'shared/search_bar'
      - if @episode
        .audio-player= render 'shared/audio_player'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.right-links
        = render 'layouts/navigation_links'
        

app/views/layouts/_navigation_links.html.haml
%li.search-bar.visible-xs-block.mobile= render 'shared/search_bar'
%li= link_to 'Episodes', episodes_path
- if user_signed_in?
  %li= link_to 'Sign out', signout_path
- else
  %li= link_to 'Sign in', signin_path
- if user_signed_in?
  - if current_user.admin?
    %li= link_to 'Admin', rails_admin.dashboard_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = yield :facebook_meta
    %title= content_for?(:title) ? yield(:title) : 'UYD Archive'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Uhh Yeah Dude Archive'}"}
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = auto_discovery_link_tag(:rss, episodes_url(format: :rss, by_direction: :desc))
  %body.container
    #fb-root
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield